### PR TITLE
Regtest: add --stop-on-failed-test option

### LINKED ISSUE #22: An option to stop on first error
There's already the `--vital` option, which stops tests on first error, but it still executes the other tests after that.

When errors are found, I would find it convenient to have the option to execute the test file again, but instead of executing all tests, just stop when the first error is met. This, combined with `--verbose`, provides the following efficient test fixing process:

1. Run tests (not verbose). Notice there are errors.
2. Run tests again (verbose), stopping on first error. 
3. Fix the issue that is before your eyes.
4. Goto 2. until there are no more failures.

I currently do this with the `--vital` option but it only works if the failing test is the last executed. I know I could tell RegTest to execute just the test that is failing, but the idea is that I don't want to copy the test ID for each failing test. One or several tests are failing? I just add `--verbose` and (for example) `--stop-on-error`, and I'm ready to fix.

Adjacent to this request would be my wish for the ability to see the full expected output for `LiteralCheck` errors, rather than elided output, when `--verbose` is given (and for other types of checks, if output is susceptible to being elided). Otherwise, it's not always clear from the verbose console output what the difference between actual output and expected output was.

### PR DESCRIPTION
**Pull request by stormi**
Fixes #22

### CODE REVIEW

**Comment by stormi** [comment]
Gentle prod :)

**Comment by erkyrath** [comment]
Ok, let me remember what's going on here...

My problem is that the difference between --vital and --stop-on-failed is confusing. They're both described as "stop when an error happens". If the explanation is "well, the test keeps running and then stops later", then something's wrong with the problem definition.

The whole point of a vital test is that it stops the test run. It doesn't stop *all* test runs, but that's because later test runs aren't broken. You might mark a test as `{vital}` (or use --vital) if it's going to cause a whole bunch of meaningless failures after it, but that doesn't apply to separate runs.

What you want is to run all your tests and fix the first error, but do you need a flag for that? You could run all the tests with --vital and fix the _last_ error, which is the one visible on the screen. Repeat until there are no more errors.

I could maybe imagine saying `--vital 2` or `--vital --vital` to mean "*really* exit as soon as an error happens". That would at least be easy to explain.

**Comment by stormi** [comment]
I tried to explain my development process here: https://github.com/erkyrath/plotex/issues/22 and to document the difference with `--vital` both in the help and documentation, but it looks like I failed.

I work in a console, with tests written in advance, before it's implemented in the game itself. In the console, I execute the tests, fix the first error, re-run the tests, fix the next error, etc. To avoid extra steps, I run the tests with `-v` so that I get the full context of the error. That's why I need the test run to stop immediately, otherwise the flood of output caused by the next tests invisibilizes the relevant error output.

`--vital 2` or `--vital --vital` looks good to me if you think it's a better syntax.

**Comment by erkyrath** [comment]
I saw your explanation, but it's not obvious to me why re-running a specific failing test is any harder.

However, I've added the feature as `--vital --vital`.

We now also display the line number of a check as part of its failure report. And I've done the thing where check failure reports are not abbreviated to 32 characters in `--verbose` mode.

**Comment by stormi** [comment]
> it's not obvious to me why re-running a specific failing test is any harder

When you have dozens of tests to fix because you wrote them in advance, the ability to run just one command instead of two per failure is a noticeable advantage. You fix, and then you just have to re-run the exact same command.

image

Now I have everything I need to fix either the test or the code right in front of my eyes, directly.

So thanks for adding the feature!

**Pull request closed without merging**
